version: '2'
services:
  backend:
    build: ./backend
    command: bundle exec rails s -p 3003 -b '0.0.0.0'
    volumes:
      - ./backend:/myapp/backend
    ports:
      - "3003:3003"

  frontend:
    build: ./frontend
    command: yarn run dev
    volumes:
      - ./frontend:/myapp/frontend
    ports:
      - "8080:8080"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
    links:
      - frontend:frontend
